name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main  # mainブランチに変更があったときにトリガー

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: '<AzureのApp Service名>'  # App Service名を指定
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # 秘密情報を使用
